Web.GameStoreMVC/Controllers/AdminGamesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web.GameStoreMVC.Models.Domain;
using Web.GameStoreMVC.Models.ViewModels;
using Web.GameStoreMVC.Repositories;

namespace Web.GameStoreMVC.Controllers
{
	[Authorize(Roles="Admin")]
	public class AdminGamesController : Controller
	{
		private readonly IGameRepository _gameRepository;
		private readonly IGenreRepository _genreRepository;
		private readonly ILanguageRepository _languageRepository;
		private readonly IPlatformRepository _platformRepository;

		public AdminGamesController(IGameRepository gameRepository,
			IGenreRepository genreRepository,
			ILanguageRepository languageRepository,
			IPlatformRepository platformRepository)
		{
			_gameRepository = gameRepository;
			_genreRepository = genreRepository;
			_languageRepository = languageRepository;
			_platformRepository = platformRepository;
		}

		[HttpGet]
		public async Task<IActionResult> Add()
		{
			var genres = await _genreRepository.GetAllAsync();
			var languages = await _languageRepository.GetAllAsync();
			var platforms = await _platformRepository.GetAllAsync();

			var viewModel = new AdminGameAddRequest
			{
				Genres = genres.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }),
				Languages = languages.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }),
				Platforms = platforms.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() })
			};

			return View(viewModel);
		}

		[HttpPost]
		public async Task<IActionResult> Add(AdminGameAddRequest adminGameAddRequest)
		{
			var game = new Game
			{
				Name = adminGameAddRequest.Name,
				Description = adminGameAddRequest.Description,
				ShortDescription = adminGameAddRequest.ShortDescription,
				SystemRequirements = adminGameAddRequest.SystemRequirements,
				Developer = adminGameAddRequest.Developer,
				Price = adminGameAddRequest.Price,
				YearOfRelease = adminGameAddRequest.YearOfRelease,
				ImageUrl = adminGameAddRequest.ImageUrl
			};

			var selectedGenres = new List<Genre>();
			var selectedLanguages = new List<Language>();
			var selectedPlatforms = new List<Platform>();

			foreach (var genre in adminGameAddRequest.SelectedGenres)
			{
				var selectedGenre = Guid.Parse(genre);
				var existingGenre = await _genreRepository.GetAsync(selectedGenre);

				if (existingGenre != null)
				{
					selectedGenres.Add(existingGenre);
				}
			}

			foreach (var language in adminGameAddRequest.SelectedLanguages)
			{
				var selectedlanguage = Guid.Parse(language);
				var existinglanguage = await _languageRepository.GetAsync(selectedlanguage);

				if (existinglanguage != null)
				{
					selectedLanguages.Add(existinglanguage);
				}
			}

			foreach (var platform in adminGameAddRequest.SelectedPlatforms)
			{
				var selectedPlatform = Guid.Parse(platform);
				var existingPlatform = await _platformRepository.GetAsync(selectedPlatform);

				if (existingPlatform != null)
				{
					selectedPlatforms.Add(existingPlatform);
				}
			}

			game.Genres = selectedGenres;
			game.Languages = selectedLanguages;
			game.Platforms = selectedPlatforms;

			await _gameRepository.AddAsync(game);
			return RedirectToAction(nameof(List));
		}

		[HttpGet]
		public async Task<IActionResult> List(int pageSize = 3, int pageNumber = 1)
		{
			var totalRecords = await _gameRepository.GetCountAsync();
			var totalPages = Math.Ceiling((decimal)totalRecords / pageSize);

			if (pageNumber > totalPages)
			{
				pageNumber--;
			}

			if (pageNumber < 1)
			{
				pageNumber++;
			}

			ViewBag.TotalPages = totalPages;
			ViewBag.PageSize = pageSize;
			ViewBag.PageNumber = pageNumber;

			var games = await _gameRepository.GetAllAsync(pageSize:pageSize,pageNumber:pageNumber);
			return View(games);
		}

		[HttpGet]
		public async Task<IActionResult> Edit(Guid id)
		{
			var game = await _gameRepository.GetAsync(id);
			var genres = await _genreRepository.GetAllAsync();
			var languages = await _languageRepository.GetAllAsync();
			var platforms = await _platformRepository.GetAllAsync();

			if (game != null)
			{
				var editedGame = new AdminEditGameRequest
				{
					Id = game.Id,
					Name = game.Name,
					Description = game.Description,
					ShortDescription = game.ShortDescription,
					SystemRequirements = game.SystemRequirements,
					Developer = game.Developer,
					Price = game.Price,
					YearOfRelease = game.YearOfRelease,
					ImageUrl = game.ImageUrl,
					Genres = genres.Select(x => new SelectListItem
					{
						Text = x.Name,
						Value = x.Id.ToString()
					}),
					SelectedGenres = game.Genres.Select(x => x.Id.ToString()).ToArray(),


					Languages = languages.Select(x => new SelectListItem
					{
						Text = x.Name,
						Value = x.Id.ToString()
					}),
					SelectedLanguages = game.Languages.Select(x => x.Id.ToString()).ToArray(),


					Platforms = platforms.Select(x => new SelectListItem
					{
						Text = x.Name,
						Value = x.Id.ToString()
					}),
					SelectedPlatforms = game.Platforms.Select(x => x.Id.ToString()).ToArray()
				};
				return View(editedGame);
			}
			return View(null);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(AdminEditGameRequest adminEditGameRequest)
		{
			var game = new Game
			{
				Id = adminEditGameRequest.Id,
				Name = adminEditGameRequest.Name,
				Description = adminEditGameRequest.Description,
				ShortDescription = adminEditGameRequest.ShortDescription,
				SystemRequirements = adminEditGameRequest.SystemRequirements,
				Developer = adminEditGameRequest.Developer,
				Price = adminEditGameRequest.Price,
				YearOfRelease = adminEditGameRequest.YearOfRelease,
				ImageUrl = adminEditGameRequest.ImageUrl
			};

			var editedGenres = new List<Genre>();
			var editedLanguages = new List<Language>();
			var editedPlatforms = new List<Platform>();

			foreach (var selectedGenre in adminEditGameRequest.SelectedGenres)
			{
				if (Guid.TryParse(selectedGenre, out var genreId))
				{
					var foundGenre = await _genreRepository.GetAsync(genreId);

					if (foundGenre != null)
					{
						editedGenres.Add(foundGenre);
					}
				}
			}

			foreach (var selectedLanguage in adminEditGameRequest.SelectedLanguages)
			{
				if (Guid.TryParse(selectedLanguage, out var languageId))
				{
					var foundLanguage = await _languageRepository.GetAsync(languageId);

					if (foundLanguage != null)
					{
						editedLanguages.Add(foundLanguage);
					}
				}
			}

			foreach (var selectedPlatform in adminEditGameRequest.SelectedPlatforms)
			{
				if (Guid.TryParse(selectedPlatform, out var platformId))
				{
					var foundPlatform = await _platformRepository.GetAsync(platformId);

					if (foundPlatform != null)
					{
						editedPlatforms.Add(foundPlatform);
					}
				}
			}

			game.Genres = editedGenres;
			game.Languages = editedLanguages;
			game.Platforms = editedPlatforms;

			var updatedGame = await _gameRepository.UpdateAsync(game);

			if (updatedGame != null)
			{
				return RedirectToAction(nameof(List));
			}

			return RedirectToAction(nameof(Edit), new { id = adminEditGameRequest.Id });
		}

		[HttpPost]
		public async Task<IActionResult> Delete(AdminEditGameRequest editGameRequest)
		{
			var deletedGame = await _gameRepository.DeleteAsync(editGameRequest.Id);

			if (deletedGame != null)
			{
				return RedirectToAction(nameof(List));
			}

			return RedirectToAction(nameof(Edit), new { id = editGameRequest.Id });
		}
	}
}

Web.GameStoreMVC/Controllers/AdminGenreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web.GameStoreMVC.Models.Domain;
using Web.GameStoreMVC.Models.ViewModels;
using Web.GameStoreMVC.Repositories;

namespace Web.GameStoreMVC.Controllers
{
	[Authorize(Roles ="Admin")]
	public class AdminGenreController : Controller
	{
		private readonly IGenreRepository _genreRepository;

		public AdminGenreController(IGenreRepository genreRepository)
		{
			_genreRepository = genreRepository;
		}

		[HttpGet]
		public IActionResult Add()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Add(AddGenreRequest addGenreRequest)
		{
			if (ModelState.IsValid)
			{
				var genre = new Genre
				{
					Name = addGenreRequest.Name
				};

				await _genreRepository.AddAsync(genre);

				return RedirectToAction(nameof(List));
			}
			return View();
		}

		[HttpGet]
		public async Task<IActionResult> List(int pageNumber = 1, int pageSize = 3)
		{
			var totalRecords = await _genreRepository.GetCountAsync();
			var totalPages = Math.Ceiling((decimal)totalRecords / pageSize);

			if (pageNumber > totalPages)
			{
				pageNumber--;
			}

			if (pageNumber < 1)
			{
				pageNumber++;
			}

			ViewBag.TotalPages = totalPages;
			ViewBag.PageSize = pageSize;
			ViewBag.PageNumber = pageNumber;

			var genres = await _genreRepository.GetAllAsync(pageNumber:pageNumber, pageSize:pageSize);
			return View(genres);
		}

		[HttpGet]
		public async Task<IActionResult> Edit(Guid id)
		{
			var genre = await _genreRepository.GetAsync(id);

			if (genre != null)
			{
				var editGenreRequest = new EditGenreRequest
				{
					Id = genre.Id,
					Name = genre.Name
				};
				return View(editGenreRequest);
			}

			return View(null);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(EditGenreRequest editGenreRequest)
		{
			var genre = new Genre
			{
				Id = editGenreRequest.Id,
				Name = editGenreRequest.Name
			};
			var updatedGenre = await _genreRepository.UpdateAsync(genre);

			return RedirectToAction(nameof(List), new { id = editGenreRequest.Id });
		}

		[HttpPost]
		public async Task<IActionResult> Delete(EditGenreRequest editGenreRequest)
		{
			var deletedGenre = await _genreRepository.DeleteAsync(editGenreRequest.Id);

			if(deletedGenre != null)
			{
				return RedirectToAction(nameof(List));
			}

			return RedirectToAction(nameof(List), new {id = editGenreRequest.Id});
		}
	}
}

Web.GameStoreMVC/Controllers/AdminLanguageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web.GameStoreMVC.Models.Domain;
using Web.GameStoreMVC.Models.ViewModels;
using Web.GameStoreMVC.Repositories;

namespace Web.GameStoreMVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminLanguageController : Controller
    {
        private readonly ILanguageRepository _languageRepository;

        public AdminLanguageController(ILanguageRepository languageRepository)
        {
            _languageRepository = languageRepository;
        }

        [HttpGet]
        public async Task<IActionResult> List(int pageNumber = 1, int pageSize = 3)
        {
			var totalRecords = await _languageRepository.GetCountAsync();
			var totalPages = Math.Ceiling((decimal)totalRecords / pageSize);

			if (pageNumber > totalPages)
			{
				pageNumber--;
			}

			if (pageNumber < 1)
			{
				pageNumber++;
			}

			ViewBag.TotalPages = totalPages;
			ViewBag.PageSize = pageSize;
			ViewBag.PageNumber = pageNumber;

			var languages = await _languageRepository.GetAllAsync(pageNumber:pageNumber, pageSize:pageSize);

            return View(languages);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddLanguageRequest addLanguageRequest)
        {
            if(ModelState.IsValid)
            {
                var language = new Language
                {
                    Name = addLanguageRequest.Name
                };

                await _languageRepository.AddAsync(language);
                return RedirectToAction(nameof(List));
            }

            return View();
        }

        [HttpGet] 
        public async Task<IActionResult> Edit(Guid id)
        {
            var language = await _languageRepository.GetAsync(id);

            if(language != null) 
            {
                var updatedLanguage = new EditLanguageRequest
                {
                    Id = language.Id,
                    Name = language.Name
                };
                return View(updatedLanguage);
            }

            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditLanguageRequest editLanguageRequest)
        {
            var language = new Language
            {
                Id = editLanguageRequest.Id,
                Name = editLanguageRequest.Name
            };
            await _languageRepository.UpdateAsync(language);

            return RedirectToAction(nameof(List), new {id = editLanguageRequest.Id});
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditGenreRequest editGenreRequest)
        {
            var deletedGenre = await _languageRepository.DeleteAsync(editGenreRequest.Id);

            if(deletedGenre != null)
            {
                return RedirectToAction(nameof(List));
            }

            return RedirectToAction(nameof(List), new {id = editGenreRequest.Id});
        }
    }
}

Web.GameStoreMVC/Controllers/AdminPlatformsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web.GameStoreMVC.Models.Domain;
using Web.GameStoreMVC.Models.ViewModels;
using Web.GameStoreMVC.Repositories;

namespace Web.GameStoreMVC.Controllers
{
	[Authorize(Roles = "Admin")]
	public class AdminPlatformsController : Controller
	{
		private readonly IPlatformRepository _platformRepository;

		public AdminPlatformsController(IPlatformRepository platformRepository)
		{
			_platformRepository = platformRepository;
		}

		[HttpGet]
		public async Task<IActionResult> List(int pageNumber = 1, int pageSize = 3)
		{
			var totalRecords = await _platformRepository.GetCountAsync();
			var totalPages = Math.Ceiling((decimal)totalRecords / pageSize);

			if (pageNumber > totalPages)
			{
				pageNumber--;
			}

			if (pageNumber < 1)
			{
				pageNumber++;
			}

			ViewBag.TotalPages = totalPages;
			ViewBag.PageSize = pageSize;
			ViewBag.PageNumber = pageNumber;

			var platforms = await _platformRepository.GetAllAsync(pageNumber:pageNumber, pageSize:pageSize);
			return View(platforms);
		}

		[HttpGet]
		public IActionResult Add()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Add(AddPlatformRequest addPlatformRequest)
		{
			if (ModelState.IsValid)
			{
				var platform = new Platform
				{
					Name = addPlatformRequest.Name
				};

				await _platformRepository.AddAsync(platform);
				return RedirectToAction(nameof(List));
			}

			return View();
		}

		[HttpGet]
		public async Task<IActionResult> Edit(Guid id)
		{
			var platform = await _platformRepository.GetAsync(id);

			if (platform != null)
			{
				var editPlatformRequest = new EditPlatformRequest
				{
					Id = platform.Id,
					Name = platform.Name,
				};
				return View(editPlatformRequest);
			}

			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Edit(EditPlatformRequest editPlatformRequest)
		{
			var platform = new Platform
			{
				Id = editPlatformRequest.Id,
				Name = editPlatformRequest.Name,
			};
			var updatedPlatform = await _platformRepository.UpdateAsync(platform);

			return RedirectToAction(nameof(List), new { Id = platform.Id });
		}

		public async Task<IActionResult> Delete(EditPlatformRequest editPlatformRequest)
		{
			var existingPlatform = await _platformRepository.DeleteAsync(editPlatformRequest.Id);

			if (existingPlatform != null)
			{
				return RedirectToAction(nameof(List));

			}

			return RedirectToAction(nameof(List), new { Id = editPlatformRequest.Id });
		}
	}
}

Web.GameStoreMVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Web.GameStoreMVC</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Web.GameStoreMVC.styles.css" asp-append-version="true" />
	<link href='https://cdn.jsdelivr.net/npm/froala-editor@4.0.10/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
	<script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@4.0.10/js/froala_editor.pkgd.min.js'></script>
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						@if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
						{
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
									Admin
								</a>
								<ul class="dropdown-menu">
									@if (signInManager.IsSignedIn(User) && User.IsInRole("SuperAdmin"))
									{
										<li>
											<a class="dropdown-item"
											   asp-controller="AdminUsers"
											   asp-action="List">Все пользователи</a>
										</li>
									}
									<li>
										<a class="dropdown-item"
										   asp-controller="AdminGames"
										   asp-action="List">Все игры</a>
									</li>
									<li>
										<a class="dropdown-item"
										   asp-controller="AdminGames"
										   asp-action="Add">Добавить игру</a>
									</li>
									<li>
										<a class="dropdown-item"
										   asp-controller="AdminGenre"
										   asp-action="Add">Добавить жанр</a>
									</li>
									<li>
										<a class="dropdown-item"
										   asp-controller="AdminGenre"
										   asp-action="List">Все жанры</a>
									</li>
									<li>
										<a class="dropdown-item"
										   asp-controller="AdminLanguage"
										   asp-action="Add">Добавить язык</a>
									</li>
									<li>
										<a class="dropdown-item"
										   asp-controller="AdminLanguage"
										   asp-action="List">Все языки</a>
									</li>
									<li>
										<a class="dropdown-item"
										   asp-controller="AdminPlatforms"
										   asp-action="Add">Добавить платформу</a>
									</li>
									<li>
										<a class="dropdown-item"
										   asp-controller="AdminPlatforms"
										   asp-action="List">Все платформы</a>
									</li>
								</ul>
							</li>
						}
					</ul>
					<div class="d-flex align-items-center">
						@if (signInManager.IsSignedIn(User))
						{
							<div class="me-3 text-light">
								@User?.Identity?.Name
							</div>

							<a class="btn me-3 bg-dark text-light"
							   asp-area=""
							   asp-controller="Account"
							   asp-action="Logout">Выйти</a>
						}
						else
						{
							<a class="btn me-3 bg-dark text-light"
							   asp-area=""
							   asp-controller="Account"
							   asp-action="Register">Регистрация</a>

							<a class="btn me-3 bg-dark text-light"
							   asp-area=""
							   asp-controller="Account"
							   asp-action="Login">Войти</a>
						}
					</div>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			Магазин Ретро-Игр
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>